"""UI Events — Two-way communication between workers and UI (Sprint 3)."""
from enum import Enum

class UIEvent(str, Enum):
    """Worker -> UI direction events."""
    PORT_DISCOVERED = "ui.port.discovered"
    PORT_UPDATE = "ui.port.update"
    PORT_REMOVED = "ui.port.removed"
    PORT_EXCLUDED = "ui.port.excluded"
    PORT_INCLUDED = "ui.port.included"
    WORKER_STARTED = "ui.worker.started"
    WORKER_STOPPED = "ui.worker.stopped"
    LOG_APPEND = "ui.log.append"
    FOOTER_UPDATE = "ui.footer.update"
    SETTINGS_CHANGED = "ui.settings.changed"
    SCAN_COMPLETE = "ui.scan.complete"
    MODEM_ONLINE = "ui.modem.online"
    MODEM_OFFLINE = "ui.modem.offline"
    AUTO_RUN_CHANGED = "ui.auto_run.changed"
    MASS_PROGRESS = "ui.mass.progress"
    MASS_COMPLETE = "ui.mass.complete"
    DB_LOOKUP_RESULT = "ui.db.lookup.result"
    TASK = "ui.task"

class CommandEvent(str, Enum):
    """UI -> Worker direction events."""
    PORT_ON = "cmd.port.on"
    PORT_OFF = "cmd.port.off"
    PORT_EXCLUDE = "cmd.port.exclude"
    PORT_INCLUDE = "cmd.port.include"
    CEK_NOMOR = "cmd.cek_nomor"
    CEK_STATUS = "cmd.cek_status"
    CEK_NIK = "cmd.cek_nik"
    CARI_KK = "cmd.cari_kk"
    REAKTIVASI = "cmd.reaktivasi"
    REACTIVATE = "cmd.reactivate"
    RESTART_ALL = "cmd.restart_all"
    RESTART_PORT = "cmd.restart_port"
    STOP_ALL = "cmd.stop_all"
    RESET_MODEM = "cmd.reset_modem"
    FORCE_RETRY = "cmd.force_retry"
    SAVE_CONFIG = "cmd.save_config"
    AUTO_RUN_TOGGLE = "cmd.auto_run.toggle"
    DB_LOOKUP_NIK = "cmd.db.lookup_nik"
    DB_LOOKUP_KK = "cmd.db.lookup_kk"
    CEK_LIMIT = "cmd.cek_limit"
    MASS_REAKTIVASI = "cmd.mass.reaktivasi"
    MASS_CEK_NOMOR = "cmd.mass.cek_nomor"
